sync:
    image: n3llyb0y/wait
    links:
        - ari
        - ctid-ng
    environment:
        PORTS: "5039 9500"

ari:
    image: p0bailey/docker-flask
    expose:
        - "5039"
    volumes:
        - "./ari:/usr/local/share/ari"
        - "./ssl/ari:/usr/local/share/ari-ssl"
    command: "python /usr/local/share/ari/mock-ari.py 5039"

ctid-ng:
    image: xivo-ctid-ng-test
    volumes:
        - "../../..:/usr/src/xivo-ctid-ng"
        - "./etc/xivo-ctid-ng:/etc/xivo-ctid-ng"
        - "./ssl/localhost:/usr/share/xivo-certs"
    ports:
        - "9500:9500"
    links:
        - ari
